;;; verilog-ext-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from verilog-ext.el

(autoload 'verilog-ext-mode-setup "verilog-ext" "\
Setup `verilog-ext-mode' depending on enabled features." t)
(autoload 'verilog-ext-mode "verilog-ext" "\
Minor mode for editing SystemVerilog files.

\\{verilog-ext-mode-map}

This is a minor mode.  If called interactively, toggle the
`Verilog-Ext mode' mode.  If the prefix argument is positive,
enable the mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable
the mode if ARG is nil, omitted, or is a positive number.
Disable the mode if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `verilog-ext-mode'.

The mode's hook is called both when the mode is enabled and when
it is disabled.

(fn &optional ARG)" t)
(register-definition-prefixes "verilog-ext" '("verilog-ext-"))


;;; Generated autoloads from verilog-ext-beautify.el

(register-definition-prefixes "verilog-ext-beautify" '("verilog-ext-beautify-"))


;;; Generated autoloads from verilog-ext-block-end-comments.el

(register-definition-prefixes "verilog-ext-block-end-comments" '("verilog-ext-block-end-"))


;;; Generated autoloads from verilog-ext-capf.el

(register-definition-prefixes "verilog-ext-capf" '("verilog-ext-capf"))


;;; Generated autoloads from verilog-ext-compile.el

(register-definition-prefixes "verilog-ext-compile" '("verilog-ext-"))


;;; Generated autoloads from verilog-ext-eglot.el

(register-definition-prefixes "verilog-ext-eglot" '("verilog-ext-eglot-"))


;;; Generated autoloads from verilog-ext-flycheck.el

(register-definition-prefixes "verilog-ext-flycheck" '("verilog-ext-flycheck-"))


;;; Generated autoloads from verilog-ext-font-lock.el

(register-definition-prefixes "verilog-ext-font-lock" '("verilog-ext-font-lock-"))


;;; Generated autoloads from verilog-ext-formatter.el

(register-definition-prefixes "verilog-ext-formatter" '("verilog-ext-formatter-"))


;;; Generated autoloads from verilog-ext-hierarchy.el

(register-definition-prefixes "verilog-ext-hierarchy" '("verilog-ext-hierarchy-"))


;;; Generated autoloads from verilog-ext-hs.el

(register-definition-prefixes "verilog-ext-hs" '("verilog-ext-hs-"))


;;; Generated autoloads from verilog-ext-imenu.el

(register-definition-prefixes "verilog-ext-imenu" '("verilog-ext-imenu-"))


;;; Generated autoloads from verilog-ext-lsp.el

(register-definition-prefixes "verilog-ext-lsp" '("verilog-ext-lsp-"))


;;; Generated autoloads from verilog-ext-nav.el

(register-definition-prefixes "verilog-ext-nav" '("verilog-ext-"))


;;; Generated autoloads from verilog-ext-ports.el

(register-definition-prefixes "verilog-ext-ports" '("verilog-ext-ports-"))


;;; Generated autoloads from verilog-ext-tags.el

(register-definition-prefixes "verilog-ext-tags" '("verilog-ext-tags-"))


;;; Generated autoloads from verilog-ext-template.el

(register-definition-prefixes "verilog-ext-template" '("verilog-ext-" "with-verilog-ext-template"))


;;; Generated autoloads from verilog-ext-time-stamp.el

(register-definition-prefixes "verilog-ext-time-stamp" '("verilog-ext-time-stamp-"))


;;; Generated autoloads from verilog-ext-typedef.el

(register-definition-prefixes "verilog-ext-typedef" '("verilog-ext-typedef-"))


;;; Generated autoloads from verilog-ext-utils.el

(register-definition-prefixes "verilog-ext-utils" '("verilog-ext-"))


;;; Generated autoloads from verilog-ext-which-func.el

(register-definition-prefixes "verilog-ext-which-func" '("verilog-ext-which-func"))


;;; Generated autoloads from verilog-ext-xref.el

(register-definition-prefixes "verilog-ext-xref" '("verilog-ext-xref-"))

;;; End of scraped data

(provide 'verilog-ext-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; verilog-ext-autoloads.el ends here
