;;; chruby-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from chruby.el

(autoload 'chruby "chruby" "\
If name is given, activate the given Ruby. Else, return the currently
 activated Ruby

(fn &optional NAME)")
(autoload 'chruby-use "chruby" "\
choose what ruby you want to activate

(fn RUBY-VERSION)" t)
(autoload 'chruby-use-corresponding "chruby" "\
search for .ruby-version and activate the corresponding ruby" t)
(register-definition-prefixes "chruby" '("chruby-"))

;;; End of scraped data

(provide 'chruby-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; chruby-autoloads.el ends here
