;;; veri-kompass-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from veri-kompass.el

(autoload 'veri-kompass "veri-kompass" "\
Enable Veri-Kompass.
Veri-Kompass is a verilog codebase navigation facility.
The codebase to be parsed will be in directory DIR.
The decendent parsing will start from module TOP-NAME.

(fn DIR &optional TOP-NAME)" t)
(register-definition-prefixes "veri-kompass" '("veri-kompass-"))

;;; End of scraped data

(provide 'veri-kompass-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; veri-kompass-autoloads.el ends here
